/*
 *  include/fake_dl.h generated by build.sh
 *
 *  Copyright (C) SplinterGU (Fenix/BennuGD) (Since 2006)
 *  Copyright (C) 2002-2006 Fenix Team (Fenix)
 *  Copyright (C) 1999-2002 José Luis Cebrián Pagüe (Fenix)
 *
 *  This file is part of Bennu Game Development
 *
 *  This software is provided 'as-is', without any express or implied
 *  warranty. In no event will the authors be held liable for any damages
 *  arising from the use of this software.
 *
 *  Permission is granted to anyone to use this software for any purpose,
 *  including commercial applications, and to alter it and redistribute it
 *  freely, subject to the following restrictions:
 *
 *     1. The origin of this software must not be misrepresented; you must not
 *     claim that you wrote the original software. If you use this software
 *     in a product, an acknowledgment in the product documentation would be
 *     appreciated but is not required.
 *
 *     2. Altered source versions must be plainly marked as such, and must not be
 *     misrepresented as being the original software.
 *
 *     3. This notice may not be removed or altered from any source
 *     distribution.
 *
 */    

#ifndef __FAKE_DL_H
#define __FAKE_DL_H
 
#include <bgddl.h>
 
#ifdef __BGDC__
#include "libbggfx_exports.h"
#include "libbginput_exports.h"
#include "libmod_debug_exports.h"
#include "libmod_gfx_exports.h"
#include "libmod_input_exports.h"
#include "libmod_misc_exports.h"
#include "libmod_net_exports.h"
#include "libmod_sound_exports.h"
#endif
 
#ifndef __BGDC__
/* ---------- globals_fixup ---------- */
 
extern DLVARFIXUP libbggfx_globals_fixup[];
extern DLVARFIXUP libbginput_globals_fixup[];
extern DLVARFIXUP libmod_debug_globals_fixup[];
extern DLVARFIXUP libmod_gfx_globals_fixup[];
extern DLVARFIXUP libmod_misc_globals_fixup[];
extern DLVARFIXUP libmod_sound_globals_fixup[];
 
/* ---------- locals_fixup ---------- */
 
extern DLVARFIXUP libbggfx_locals_fixup[];
extern DLVARFIXUP libmod_debug_locals_fixup[];
extern DLVARFIXUP libmod_gfx_locals_fixup[];
extern DLVARFIXUP libmod_misc_locals_fixup[];
 
/* ---------- functions_exports ---------- */
 
extern DLSYSFUNCS libmod_debug_functions_exports[];
extern DLSYSFUNCS libmod_gfx_functions_exports[];
extern DLSYSFUNCS libmod_input_functions_exports[];
extern DLSYSFUNCS libmod_misc_functions_exports[];
extern DLSYSFUNCS libmod_net_functions_exports[];
extern DLSYSFUNCS libmod_sound_functions_exports[];
 
/* ---------- module_initialize ---------- */
 
extern void libbggfx_module_initialize();
extern void libbginput_module_initialize();
extern void libmod_debug_module_initialize();
extern void libmod_gfx_module_initialize();
extern void libmod_misc_module_initialize();
extern void libmod_net_module_initialize();
extern void libmod_sound_module_initialize();
extern void libsdlhandler_module_initialize();
 
/* ---------- module_finalize ---------- */
 
extern void libbggfx_module_finalize();
extern void libbginput_module_finalize();
extern void libmod_debug_module_finalize();
extern void libmod_gfx_module_finalize();
extern void libmod_misc_module_finalize();
extern void libmod_net_module_finalize();
extern void libmod_sound_module_finalize();
extern void libsdlhandler_module_finalize();
 
/* ---------- instance_create_hook ---------- */
 
extern void libbggfx_instance_create_hook( INSTANCE * );
 
/* ---------- instance_destroy_hook ---------- */
 
extern void libbggfx_instance_destroy_hook( INSTANCE * );
 
/* ---------- instance_pre_execute_hook ---------- */
 
 
/* ---------- instance_pos_execute_hook ---------- */
 
 
/* ---------- process_exec_hook ---------- */
 
extern void libmod_debug_process_exec_hook( INSTANCE * );
extern void libmod_gfx_process_exec_hook( INSTANCE * );
extern void libmod_misc_process_exec_hook( INSTANCE * );
 
/* ---------- handler_hooks ---------- */
 
extern HOOK libbggfx_handler_hooks[];
extern HOOK libbginput_handler_hooks[];
extern HOOK libmod_debug_handler_hooks[];
extern HOOK libmod_misc_handler_hooks[];
extern HOOK libsdlhandler_handler_hooks[];
 
/* ---------- modules_dependency ---------- */
 
extern char * libbggfx_modules_dependency[];
extern char * libbginput_modules_dependency[];
extern char * mod_debug_modules_dependency[];
extern char * libmod_gfx_modules_dependency[];
extern char * libmod_input_modules_dependency[];
 
#endif

/* ---------- structs ---------- */

typedef struct __FAKE_DL
{
    char            * dlname;
    DLCONSTANT      * constants_def;
    char            ** types_def;
    char            ** globals_def;
    char            ** locals_def;
    DLVARFIXUP      * globals_fixup;
    DLVARFIXUP      * locals_fixup;
    DLSYSFUNCS      * functions_exports;
    void            (* module_initialize)();
    void            (* module_finalize)();
    void            (* instance_create_hook)(INSTANCE *);
    void            (* instance_destroy_hook)(INSTANCE *);
    void            (* instance_pre_execute_hook)(INSTANCE *);
    void            (* instance_pos_execute_hook)(INSTANCE *);
    void            (* process_exec_hook)(INSTANCE *);
    HOOK            * handler_hooks;
    char           ** modules_dependency;
} __FAKE_DL;

/* ---------- FAKE DYNAMIC LIBRARY ---------- */
 
__FAKE_DL __fake_dl[11];
 
/* ------------------------------------------ */
 
void fake_dl_init()
{
 
    /* -------------------- libbggfx -------------------- */
 
    __fake_dl[0].dlname                       = "libbggfx";
#ifdef __BGDC__
    __fake_dl[0].constants_def                = libbggfx_constants_def;
    __fake_dl[0].types_def                    = &libbggfx_types_def;
    __fake_dl[0].globals_def                  = &libbggfx_globals_def;
    __fake_dl[0].locals_def                   = &libbggfx_locals_def;
    __fake_dl[0].globals_fixup                = NULL;
    __fake_dl[0].locals_fixup                 = NULL;
#else
    __fake_dl[0].constants_def                = NULL;
    __fake_dl[0].types_def                    = NULL;
    __fake_dl[0].globals_def                  = NULL;
    __fake_dl[0].locals_def                   = NULL;
    __fake_dl[0].globals_fixup                = libbggfx_globals_fixup;
    __fake_dl[0].locals_fixup                 = libbggfx_locals_fixup;
#endif
    __fake_dl[0].functions_exports            = NULL;
#ifdef __BGDC__
    __fake_dl[0].module_initialize            = NULL;
    __fake_dl[0].module_finalize              = NULL;
    __fake_dl[0].instance_create_hook         = NULL;
    __fake_dl[0].instance_destroy_hook        = NULL;
    __fake_dl[0].instance_pre_execute_hook    = NULL;
    __fake_dl[0].instance_pos_execute_hook    = NULL;
    __fake_dl[0].process_exec_hook            = NULL;
    __fake_dl[0].handler_hooks                = NULL;
#else
    __fake_dl[0].module_initialize            = libbggfx_module_initialize;
    __fake_dl[0].module_finalize              = libbggfx_module_finalize;
    __fake_dl[0].instance_create_hook         = libbggfx_instance_create_hook;
    __fake_dl[0].instance_destroy_hook        = libbggfx_instance_destroy_hook;
    __fake_dl[0].instance_pre_execute_hook    = NULL;
    __fake_dl[0].instance_pos_execute_hook    = NULL;
    __fake_dl[0].process_exec_hook            = NULL;
    __fake_dl[0].handler_hooks                = libbggfx_handler_hooks;
#endif
    __fake_dl[0].modules_dependency           = libbggfx_modules_dependency;
  
    /* -------------------- libbginput -------------------- */
 
    __fake_dl[1].dlname                       = "libbginput";
#ifdef __BGDC__
    __fake_dl[1].constants_def                = libbginput_constants_def;
    __fake_dl[1].types_def                    = NULL;
    __fake_dl[1].globals_def                  = &libbginput_globals_def;
    __fake_dl[1].locals_def                   = NULL;
    __fake_dl[1].globals_fixup                = NULL;
    __fake_dl[1].locals_fixup                 = NULL;
#else
    __fake_dl[1].constants_def                = NULL;
    __fake_dl[1].types_def                    = NULL;
    __fake_dl[1].globals_def                  = NULL;
    __fake_dl[1].locals_def                   = NULL;
    __fake_dl[1].globals_fixup                = libbginput_globals_fixup;
    __fake_dl[1].locals_fixup                 = NULL;
#endif
    __fake_dl[1].functions_exports            = NULL;
#ifdef __BGDC__
    __fake_dl[1].module_initialize            = NULL;
    __fake_dl[1].module_finalize              = NULL;
    __fake_dl[1].instance_create_hook         = NULL;
    __fake_dl[1].instance_destroy_hook        = NULL;
    __fake_dl[1].instance_pre_execute_hook    = NULL;
    __fake_dl[1].instance_pos_execute_hook    = NULL;
    __fake_dl[1].process_exec_hook            = NULL;
    __fake_dl[1].handler_hooks                = NULL;
#else
    __fake_dl[1].module_initialize            = libbginput_module_initialize;
    __fake_dl[1].module_finalize              = libbginput_module_finalize;
    __fake_dl[1].instance_create_hook         = NULL;
    __fake_dl[1].instance_destroy_hook        = NULL;
    __fake_dl[1].instance_pre_execute_hook    = NULL;
    __fake_dl[1].instance_pos_execute_hook    = NULL;
    __fake_dl[1].process_exec_hook            = NULL;
    __fake_dl[1].handler_hooks                = libbginput_handler_hooks;
#endif
    __fake_dl[1].modules_dependency           = libbginput_modules_dependency;
  
    /* -------------------- libbgload -------------------- */
 
    __fake_dl[2].dlname                       = "libbgload";
#ifdef __BGDC__
    __fake_dl[2].constants_def                = NULL;
    __fake_dl[2].types_def                    = NULL;
    __fake_dl[2].globals_def                  = NULL;
    __fake_dl[2].locals_def                   = NULL;
    __fake_dl[2].globals_fixup                = NULL;
    __fake_dl[2].locals_fixup                 = NULL;
#else
    __fake_dl[2].constants_def                = NULL;
    __fake_dl[2].types_def                    = NULL;
    __fake_dl[2].globals_def                  = NULL;
    __fake_dl[2].locals_def                   = NULL;
    __fake_dl[2].globals_fixup                = NULL;
    __fake_dl[2].locals_fixup                 = NULL;
#endif
    __fake_dl[2].functions_exports            = NULL;
#ifdef __BGDC__
    __fake_dl[2].module_initialize            = NULL;
    __fake_dl[2].module_finalize              = NULL;
    __fake_dl[2].instance_create_hook         = NULL;
    __fake_dl[2].instance_destroy_hook        = NULL;
    __fake_dl[2].instance_pre_execute_hook    = NULL;
    __fake_dl[2].instance_pos_execute_hook    = NULL;
    __fake_dl[2].process_exec_hook            = NULL;
    __fake_dl[2].handler_hooks                = NULL;
#else
    __fake_dl[2].module_initialize            = NULL;
    __fake_dl[2].module_finalize              = NULL;
    __fake_dl[2].instance_create_hook         = NULL;
    __fake_dl[2].instance_destroy_hook        = NULL;
    __fake_dl[2].instance_pre_execute_hook    = NULL;
    __fake_dl[2].instance_pos_execute_hook    = NULL;
    __fake_dl[2].process_exec_hook            = NULL;
    __fake_dl[2].handler_hooks                = NULL;
#endif
    __fake_dl[2].modules_dependency           = NULL;
  
    /* -------------------- libmod_debug -------------------- */
 
    __fake_dl[3].dlname                       = "libmod_debug";
#ifdef __BGDC__
    __fake_dl[3].constants_def                = NULL;
    __fake_dl[3].types_def                    = NULL;
    __fake_dl[3].globals_def                  = NULL;
    __fake_dl[3].locals_def                   = NULL;
    __fake_dl[3].globals_fixup                = NULL;
    __fake_dl[3].locals_fixup                 = NULL;
#else
    __fake_dl[3].constants_def                = NULL;
    __fake_dl[3].types_def                    = NULL;
    __fake_dl[3].globals_def                  = NULL;
    __fake_dl[3].locals_def                   = NULL;
    __fake_dl[3].globals_fixup                = libmod_debug_globals_fixup;
    __fake_dl[3].locals_fixup                 = libmod_debug_locals_fixup;
#endif
    __fake_dl[3].functions_exports            = libmod_debug_functions_exports;
#ifdef __BGDC__
    __fake_dl[3].module_initialize            = NULL;
    __fake_dl[3].module_finalize              = NULL;
    __fake_dl[3].instance_create_hook         = NULL;
    __fake_dl[3].instance_destroy_hook        = NULL;
    __fake_dl[3].instance_pre_execute_hook    = NULL;
    __fake_dl[3].instance_pos_execute_hook    = NULL;
    __fake_dl[3].process_exec_hook            = NULL;
    __fake_dl[3].handler_hooks                = NULL;
#else
    __fake_dl[3].module_initialize            = libmod_debug_module_initialize;
    __fake_dl[3].module_finalize              = libmod_debug_module_finalize;
    __fake_dl[3].instance_create_hook         = NULL;
    __fake_dl[3].instance_destroy_hook        = NULL;
    __fake_dl[3].instance_pre_execute_hook    = NULL;
    __fake_dl[3].instance_pos_execute_hook    = NULL;
    __fake_dl[3].process_exec_hook            = libmod_debug_process_exec_hook;
    __fake_dl[3].handler_hooks                = libmod_debug_handler_hooks;
#endif
    __fake_dl[3].modules_dependency           = mod_debug_modules_dependency;
  
    /* -------------------- libmod_gfx -------------------- */
 
    __fake_dl[4].dlname                       = "libmod_gfx";
#ifdef __BGDC__
    __fake_dl[4].constants_def                = libmod_gfx_constants_def;
    __fake_dl[4].types_def                    = NULL;
    __fake_dl[4].globals_def                  = NULL;
    __fake_dl[4].locals_def                   = &libmod_gfx_locals_def;
    __fake_dl[4].globals_fixup                = NULL;
    __fake_dl[4].locals_fixup                 = NULL;
#else
    __fake_dl[4].constants_def                = NULL;
    __fake_dl[4].types_def                    = NULL;
    __fake_dl[4].globals_def                  = NULL;
    __fake_dl[4].locals_def                   = NULL;
    __fake_dl[4].globals_fixup                = libmod_gfx_globals_fixup;
    __fake_dl[4].locals_fixup                 = libmod_gfx_locals_fixup;
#endif
    __fake_dl[4].functions_exports            = libmod_gfx_functions_exports;
#ifdef __BGDC__
    __fake_dl[4].module_initialize            = NULL;
    __fake_dl[4].module_finalize              = NULL;
    __fake_dl[4].instance_create_hook         = NULL;
    __fake_dl[4].instance_destroy_hook        = NULL;
    __fake_dl[4].instance_pre_execute_hook    = NULL;
    __fake_dl[4].instance_pos_execute_hook    = NULL;
    __fake_dl[4].process_exec_hook            = NULL;
    __fake_dl[4].handler_hooks                = NULL;
#else
    __fake_dl[4].module_initialize            = libmod_gfx_module_initialize;
    __fake_dl[4].module_finalize              = libmod_gfx_module_finalize;
    __fake_dl[4].instance_create_hook         = NULL;
    __fake_dl[4].instance_destroy_hook        = NULL;
    __fake_dl[4].instance_pre_execute_hook    = NULL;
    __fake_dl[4].instance_pos_execute_hook    = NULL;
    __fake_dl[4].process_exec_hook            = libmod_gfx_process_exec_hook;
    __fake_dl[4].handler_hooks                = NULL;
#endif
    __fake_dl[4].modules_dependency           = libmod_gfx_modules_dependency;
  
    /* -------------------- libmod_input -------------------- */
 
    __fake_dl[5].dlname                       = "libmod_input";
#ifdef __BGDC__
    __fake_dl[5].constants_def                = NULL;
    __fake_dl[5].types_def                    = NULL;
    __fake_dl[5].globals_def                  = NULL;
    __fake_dl[5].locals_def                   = NULL;
    __fake_dl[5].globals_fixup                = NULL;
    __fake_dl[5].locals_fixup                 = NULL;
#else
    __fake_dl[5].constants_def                = NULL;
    __fake_dl[5].types_def                    = NULL;
    __fake_dl[5].globals_def                  = NULL;
    __fake_dl[5].locals_def                   = NULL;
    __fake_dl[5].globals_fixup                = NULL;
    __fake_dl[5].locals_fixup                 = NULL;
#endif
    __fake_dl[5].functions_exports            = libmod_input_functions_exports;
#ifdef __BGDC__
    __fake_dl[5].module_initialize            = NULL;
    __fake_dl[5].module_finalize              = NULL;
    __fake_dl[5].instance_create_hook         = NULL;
    __fake_dl[5].instance_destroy_hook        = NULL;
    __fake_dl[5].instance_pre_execute_hook    = NULL;
    __fake_dl[5].instance_pos_execute_hook    = NULL;
    __fake_dl[5].process_exec_hook            = NULL;
    __fake_dl[5].handler_hooks                = NULL;
#else
    __fake_dl[5].module_initialize            = NULL;
    __fake_dl[5].module_finalize              = NULL;
    __fake_dl[5].instance_create_hook         = NULL;
    __fake_dl[5].instance_destroy_hook        = NULL;
    __fake_dl[5].instance_pre_execute_hook    = NULL;
    __fake_dl[5].instance_pos_execute_hook    = NULL;
    __fake_dl[5].process_exec_hook            = NULL;
    __fake_dl[5].handler_hooks                = NULL;
#endif
    __fake_dl[5].modules_dependency           = libmod_input_modules_dependency;
  
    /* -------------------- libmod_misc -------------------- */
 
    __fake_dl[6].dlname                       = "libmod_misc";
#ifdef __BGDC__
    __fake_dl[6].constants_def                = libmod_misc_constants_def;
    __fake_dl[6].types_def                    = NULL;
    __fake_dl[6].globals_def                  = &libmod_misc_globals_def;
    __fake_dl[6].locals_def                   = &libmod_misc_locals_def;
    __fake_dl[6].globals_fixup                = NULL;
    __fake_dl[6].locals_fixup                 = NULL;
#else
    __fake_dl[6].constants_def                = NULL;
    __fake_dl[6].types_def                    = NULL;
    __fake_dl[6].globals_def                  = NULL;
    __fake_dl[6].locals_def                   = NULL;
    __fake_dl[6].globals_fixup                = libmod_misc_globals_fixup;
    __fake_dl[6].locals_fixup                 = libmod_misc_locals_fixup;
#endif
    __fake_dl[6].functions_exports            = libmod_misc_functions_exports;
#ifdef __BGDC__
    __fake_dl[6].module_initialize            = NULL;
    __fake_dl[6].module_finalize              = NULL;
    __fake_dl[6].instance_create_hook         = NULL;
    __fake_dl[6].instance_destroy_hook        = NULL;
    __fake_dl[6].instance_pre_execute_hook    = NULL;
    __fake_dl[6].instance_pos_execute_hook    = NULL;
    __fake_dl[6].process_exec_hook            = NULL;
    __fake_dl[6].handler_hooks                = NULL;
#else
    __fake_dl[6].module_initialize            = libmod_misc_module_initialize;
    __fake_dl[6].module_finalize              = libmod_misc_module_finalize;
    __fake_dl[6].instance_create_hook         = NULL;
    __fake_dl[6].instance_destroy_hook        = NULL;
    __fake_dl[6].instance_pre_execute_hook    = NULL;
    __fake_dl[6].instance_pos_execute_hook    = NULL;
    __fake_dl[6].process_exec_hook            = libmod_misc_process_exec_hook;
    __fake_dl[6].handler_hooks                = libmod_misc_handler_hooks;
#endif
    __fake_dl[6].modules_dependency           = NULL;
  
    /* -------------------- libmod_net -------------------- */
 
    __fake_dl[7].dlname                       = "libmod_net";
#ifdef __BGDC__
    __fake_dl[7].constants_def                = libmod_net_constants_def;
    __fake_dl[7].types_def                    = NULL;
    __fake_dl[7].globals_def                  = NULL;
    __fake_dl[7].locals_def                   = NULL;
    __fake_dl[7].globals_fixup                = NULL;
    __fake_dl[7].locals_fixup                 = NULL;
#else
    __fake_dl[7].constants_def                = NULL;
    __fake_dl[7].types_def                    = NULL;
    __fake_dl[7].globals_def                  = NULL;
    __fake_dl[7].locals_def                   = NULL;
    __fake_dl[7].globals_fixup                = NULL;
    __fake_dl[7].locals_fixup                 = NULL;
#endif
    __fake_dl[7].functions_exports            = libmod_net_functions_exports;
#ifdef __BGDC__
    __fake_dl[7].module_initialize            = NULL;
    __fake_dl[7].module_finalize              = NULL;
    __fake_dl[7].instance_create_hook         = NULL;
    __fake_dl[7].instance_destroy_hook        = NULL;
    __fake_dl[7].instance_pre_execute_hook    = NULL;
    __fake_dl[7].instance_pos_execute_hook    = NULL;
    __fake_dl[7].process_exec_hook            = NULL;
    __fake_dl[7].handler_hooks                = NULL;
#else
    __fake_dl[7].module_initialize            = libmod_net_module_initialize;
    __fake_dl[7].module_finalize              = libmod_net_module_finalize;
    __fake_dl[7].instance_create_hook         = NULL;
    __fake_dl[7].instance_destroy_hook        = NULL;
    __fake_dl[7].instance_pre_execute_hook    = NULL;
    __fake_dl[7].instance_pos_execute_hook    = NULL;
    __fake_dl[7].process_exec_hook            = NULL;
    __fake_dl[7].handler_hooks                = NULL;
#endif
    __fake_dl[7].modules_dependency           = NULL;
  
    /* -------------------- libmod_sound -------------------- */
 
    __fake_dl[8].dlname                       = "libmod_sound";
#ifdef __BGDC__
    __fake_dl[8].constants_def                = libmod_sound_constants_def;
    __fake_dl[8].types_def                    = NULL;
    __fake_dl[8].globals_def                  = &libmod_sound_globals_def;
    __fake_dl[8].locals_def                   = NULL;
    __fake_dl[8].globals_fixup                = NULL;
    __fake_dl[8].locals_fixup                 = NULL;
#else
    __fake_dl[8].constants_def                = NULL;
    __fake_dl[8].types_def                    = NULL;
    __fake_dl[8].globals_def                  = NULL;
    __fake_dl[8].locals_def                   = NULL;
    __fake_dl[8].globals_fixup                = libmod_sound_globals_fixup;
    __fake_dl[8].locals_fixup                 = NULL;
#endif
    __fake_dl[8].functions_exports            = libmod_sound_functions_exports;
#ifdef __BGDC__
    __fake_dl[8].module_initialize            = NULL;
    __fake_dl[8].module_finalize              = NULL;
    __fake_dl[8].instance_create_hook         = NULL;
    __fake_dl[8].instance_destroy_hook        = NULL;
    __fake_dl[8].instance_pre_execute_hook    = NULL;
    __fake_dl[8].instance_pos_execute_hook    = NULL;
    __fake_dl[8].process_exec_hook            = NULL;
    __fake_dl[8].handler_hooks                = NULL;
#else
    __fake_dl[8].module_initialize            = libmod_sound_module_initialize;
    __fake_dl[8].module_finalize              = libmod_sound_module_finalize;
    __fake_dl[8].instance_create_hook         = NULL;
    __fake_dl[8].instance_destroy_hook        = NULL;
    __fake_dl[8].instance_pre_execute_hook    = NULL;
    __fake_dl[8].instance_pos_execute_hook    = NULL;
    __fake_dl[8].process_exec_hook            = NULL;
    __fake_dl[8].handler_hooks                = NULL;
#endif
    __fake_dl[8].modules_dependency           = NULL;
  
    /* -------------------- libsdlhandler -------------------- */
 
    __fake_dl[9].dlname                       = "libsdlhandler";
#ifdef __BGDC__
    __fake_dl[9].constants_def                = NULL;
    __fake_dl[9].types_def                    = NULL;
    __fake_dl[9].globals_def                  = NULL;
    __fake_dl[9].locals_def                   = NULL;
    __fake_dl[9].globals_fixup                = NULL;
    __fake_dl[9].locals_fixup                 = NULL;
#else
    __fake_dl[9].constants_def                = NULL;
    __fake_dl[9].types_def                    = NULL;
    __fake_dl[9].globals_def                  = NULL;
    __fake_dl[9].locals_def                   = NULL;
    __fake_dl[9].globals_fixup                = NULL;
    __fake_dl[9].locals_fixup                 = NULL;
#endif
    __fake_dl[9].functions_exports            = NULL;
#ifdef __BGDC__
    __fake_dl[9].module_initialize            = NULL;
    __fake_dl[9].module_finalize              = NULL;
    __fake_dl[9].instance_create_hook         = NULL;
    __fake_dl[9].instance_destroy_hook        = NULL;
    __fake_dl[9].instance_pre_execute_hook    = NULL;
    __fake_dl[9].instance_pos_execute_hook    = NULL;
    __fake_dl[9].process_exec_hook            = NULL;
    __fake_dl[9].handler_hooks                = NULL;
#else
    __fake_dl[9].module_initialize            = libsdlhandler_module_initialize;
    __fake_dl[9].module_finalize              = libsdlhandler_module_finalize;
    __fake_dl[9].instance_create_hook         = NULL;
    __fake_dl[9].instance_destroy_hook        = NULL;
    __fake_dl[9].instance_pre_execute_hook    = NULL;
    __fake_dl[9].instance_pos_execute_hook    = NULL;
    __fake_dl[9].process_exec_hook            = NULL;
    __fake_dl[9].handler_hooks                = libsdlhandler_handler_hooks;
#endif
    __fake_dl[9].modules_dependency           = NULL;
 
    /* -------------------- LAST -------------------- */
 
    __fake_dl[10].dlname                       = NULL;
    __fake_dl[10].constants_def                = NULL;
    __fake_dl[10].types_def                    = NULL;
    __fake_dl[10].globals_def                  = NULL;
    __fake_dl[10].locals_def                   = NULL;
    __fake_dl[10].globals_fixup                = NULL;
    __fake_dl[10].locals_fixup                 = NULL;
    __fake_dl[10].functions_exports            = NULL;
    __fake_dl[10].module_initialize            = NULL;
    __fake_dl[10].module_finalize              = NULL;
    __fake_dl[10].instance_create_hook         = NULL;
    __fake_dl[10].instance_destroy_hook        = NULL;
    __fake_dl[10].instance_pre_execute_hook    = NULL;
    __fake_dl[10].instance_pos_execute_hook    = NULL;
    __fake_dl[10].process_exec_hook            = NULL;
    __fake_dl[10].handler_hooks                = NULL;
    __fake_dl[10].modules_dependency           = NULL;
 
}
 
/* ------------------------------------------ */
 
#endif
